version: "3.8"
services:
  app:
    env_file:
      - .env
    image: herokim97/care-bridge:latest  # Docker Hub에서 herokim97/codesix 이미지를 사용
    ports:
     - "8080:8080"
    container_name: app
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:latest   # Redis 공식 이미지
    container_name: redis_container  # 컨테이너 이름
    ports:
      - "6379:6379"       # Redis 기본 포트
    restart: always

  mysql:
    image: mysql:8.0  # 공식 MySQL 이미지 사용
    environment:
      MYSQL_DATABASE: care_bridge
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    ports:
     - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus
    privileged: true

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"

volumes:
  mysql-data:
    driver: local
  grafana-data:
    driver: local